import { DatabaseMetadata, TypeScriptSerializer, Config } from "kysely-codegen";

const config: Config = {
  numericParser: "number",
  dialect: "postgres",
  // Override the default TypeScript serializer to treat bigints (int8) as a number, matching our pg.types configuration
  serializer: {
    serializeFile: (metadata: DatabaseMetadata, dialect) => {
      const serializer = new TypeScriptSerializer({
        runtimeEnums: false,
        singularize: false,
        skipAutogeneratedFileComment: false,
        typeOnlyImports: false,
      });

      return serializer
        .serializeFile(metadata, dialect, {
          camelCase: false,
        })
        .replace(
          "export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;",
          "export type Int8 = ColumnType<number, number | string, number | string>;"
        );
    },
  },
  outFile: "./src/db/models/index.d.ts",
};

export default config;
