version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: your-numbers
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Accessible from host at localhost:5432

volumes:
  pg_data:
