/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface Users {
  email: string;
  externalId: string;
  id: Generated<string>;
}

export interface DB {
  accounts: Accounts;
  users: Users;
}
