/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<number, number | string, number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccountPartialBalances {
  accountId: string;
  balance: Generated<Int8>;
  month: number;
  year: number;
}

export interface Accounts {
  budgetId: string;
  id: Generated<string>;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface BudgetMonthlyBalances {
  balance: Generated<Int8>;
  budgetId: string;
  month: number;
  year: number;
}

export interface Budgets {
  id: Generated<string>;
  name: string;
  ownerId: string;
  timezone: Generated<string>;
}

export interface Categories {
  budgetId: string;
  groupId: string;
  id: Generated<string>;
  isIncome: Generated<boolean>;
  name: string;
  position: Generated<number>;
}

export interface CategoryGroups {
  budgetId: string;
  id: Generated<string>;
  isIncome: Generated<boolean>;
  name: string;
  position: Generated<number>;
}

export interface MonthlyCategoryBudgets {
  assignedAmount: Int8;
  balance: Generated<Int8>;
  budgetId: string;
  categoryId: string | null;
  month: number;
  updatedAt: Generated<Timestamp>;
  year: number;
}

export interface Payees {
  budgetId: string;
  id: Generated<string>;
  name: string;
}

export interface PlaidAccounts {
  access_token: string;
  account_id: string | null;
  account_name: string;
  account_subtype: string | null;
  account_type: string;
  budget_id: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  next_cursor: string | null;
  plaid_account_id: string;
  plaid_item_id: string;
  updatedAt: Generated<Timestamp>;
}

export interface Sessions {
  expire: Timestamp;
  sess: Json;
  sid: string;
}

export interface Transactions {
  accountId: string;
  amount: Generated<Int8>;
  categoryId: string | null;
  date: Timestamp;
  id: Generated<string>;
  isReconciled: Generated<boolean>;
  merchant_name: string | null;
  notes: string | null;
  payeeId: string | null;
  plaid_account_id: string | null;
  plaid_transaction_id: string | null;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  passwordHash: string;
  timeZone: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  account_partial_balances: AccountPartialBalances;
  accounts: Accounts;
  budget_monthly_balances: BudgetMonthlyBalances;
  budgets: Budgets;
  categories: Categories;
  category_groups: CategoryGroups;
  monthly_category_budgets: MonthlyCategoryBudgets;
  payees: Payees;
  plaid_accounts: PlaidAccounts;
  sessions: Sessions;
  transactions: Transactions;
  users: Users;
}
